# Number of days of inactivity before an issue becomes stale
daysUntilStale: 7
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Personal website with nodeJs,Lit Element,Webpack,Express technologies.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
